version: '3.8'

volumes:
  db:
  static_value:
  media_value:

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_postgres
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.0-alpine
    # volume и связанная с ним директория в контейнере
    volumes:
      - db:/var/lib/postgresql/data/
    # адрес файла, где хранятся переменные окружения
    env_file:
      - ./.env
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    build: ../api_yamdb
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - web

  mailcatcher:
    container_name: ${COMPOSE_PROJECT_NAME}_mailcatcher
    image: schickling/mailcatcher
    environment:
      - SMTP_PORT=${MAILCATCHER_SMTP_PORT}
      - HTTP_PORT=${MAILCATCHER_HTTP_PORT}
    ports:
      - "${MAILCATCHER_SMTP_PORT}:${MAILCATCHER_SMTP_PORT}"
      - "${MAILCATCHER_HTTP_PORT}:${MAILCATCHER_HTTP_PORT}" 
    env_file:
      - ./.env
    depends_on:
    - nginx